title:              CoDiS Research Blog
email:              codis@tugraz.at
description:        Follow current reserach of the CoDiS Lab Graz
author:             CoDiS Lab Graz
baseurl:            "/"
url:                "https://codis-lab-graz.github.io"

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
